import '../services/storage_service.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localized = {
    "English": {
      // --- Settings & Summarizer ---
      "settings": "Settings",
      "generation_mode": "Generation Mode",
      "cloud_ai": "Use Cloud AI (Recommended)",
      "cloud_ai_sub": "Requires internet for advanced AI.",
      "offline_ai_sub": "Offline mode active. Uses local algorithms.",
      "study_language": "Study Language",
      "download_req": "Offline translation requires a one-time 30MB download.",
      "download_btn": "Download Pack",
      "downloading": "Downloading ~30MB...",
      "ready_offline": "pack is downloaded and ready offline.",
      "summarizer": "Summarizer",
      "paste_notes": "Paste your study notes or upload a PDF to get a quick summary...",
      "summarize_btn": "Summarize",
      "generating": "Generating...",
      "key_takeaways": "Key Takeaways",
      "next_steps": "Next Steps",
      "flashcards": "Flashcards",
      "take_quiz": "Take Quiz",
      "ready_to_summarize": "Ready to summarize",
      
      // --- Bottom Navigation ---
      "nav_home": "Home",
      "nav_summary": "Summary",
      "nav_cards": "Cards",
      "nav_quiz": "Quiz",
      "nav_profile": "Profile",

      // --- Home Screen ---
      "hello": "Hello,",
      "ready_to_learn": "Ready to learn?",
      "pro_feature": "PRO FEATURE",
      "hero_title": "Study smarter\nwith AI Assistant",
      "hero_subtitle": "Upload notes to generate summaries, flashcards, and quizzes instantly.",
      "quick_tools": "Quick Tools",
      "recent_activity": "Recent Activity",
      "no_recent_activity": "No recent activity yet. Start studying!",
      
      // --- Flashcard Screen ---
      "study_deck": "Study Deck",
      "paste_deck": "Paste notes or upload a PDF to build your deck...",
      "pdf_btn": "PDF",
      "working": "Working...",
      "generate_cards": "Generate Cards",
      "ai_building_deck": "AI is building your deck...",
      "empty_deck": "Your deck is empty",
      "cards_remaining": "cards remaining",
      "deck_completed": "Deck Completed! 🎉 +20 XP",
      
      // --- Quiz Screen ---
      "study_quiz": "Study Quiz",
      "paste_quiz": "Paste notes or upload a PDF to generate a quiz...",
      "generate_quiz": "Generate Quiz",
      "ai_writing_quiz": "AI is writing your quiz...",
      "empty_quiz": "No quiz generated yet",
      "questions_remaining": "questions remaining",
      "quiz_completed": "Quiz Completed! 🎉 +50 XP",
      
      // --- Profile Screen ---
      "profile": "Profile",
      "current_level": "CURRENT LEVEL",
      "day_streak": "Day Streak",
      "my_stats": "My Stats",
      "quizzes_taken": "Quizzes Taken",
      "saved_pdfs": "Saved PDFs",
      "no_activity_yet": "No activity yet. Go study!",
      "no_email": "No email provided",

      // --- Onboarding Screen ---
      "skip": "Skip",
      "welcome_title": "Welcome to\nSmart Student",
      "welcome_desc": "Your AI-powered study companion. Let's make learning easier, faster, and much more fun.",
      "study_smarter_title": "Study Smarter,\nNot Harder",
      "study_smarter_desc": "Upload your PDFs or notes to instantly generate summaries, flashcards, and quizzes.",
      "create_account": "Create Account",
      "signup_desc": "Sign up to save your progress, decks, and study streaks.",
      "your_name": "Your Name",
      "email_optional": "Email Address (Optional)",
      "get_started": "Get Started",
      "continue_btn": "Continue",

      "account": "Account",
      "edit_profile": "Edit Profile",
      "data_privacy": "Data & Privacy",
      "clear_data": "Clear Study History",
      "clear_data_desc": "Reset your XP, streaks, and recent activity.",
      "logout": "Log Out",
      "cancel": "Cancel",
      "save": "Save",
      "confirm": "Confirm",
      "about_app": "About Smart Student",

      "notifications": "Notifications",
      "study_reminders": "Study Reminders",
      "reminders_sub": "Get notified to keep your streak alive.",
      "help_support": "Help & Support",
      "send_feedback": "Send Feedback",
      "privacy_policy": "Privacy Policy",
    },
    
    "Hindi": {
      // --- Settings & Summarizer ---
      "settings": "सेटिंग्स",
      "generation_mode": "जेनरेशन मोड",
      "cloud_ai": "क्लाउड एआई का उपयोग करें (अनुशंसित)",
      "cloud_ai_sub": "उन्नत एआई के लिए इंटरनेट की आवश्यकता है।",
      "offline_ai_sub": "ऑफ़लाइन मोड सक्रिय। स्थानीय एल्गोरिदम का उपयोग करता है।",
      "study_language": "अध्ययन की भाषा",
      "download_req": "ऑफ़लाइन अनुवाद के लिए एक बार 30MB डाउनलोड की आवश्यकता है।",
      "download_btn": "पैक डाउनलोड करें",
      "downloading": "डाउनलोड हो रहा है ~30MB...",
      "ready_offline": "पैक डाउनलोड हो गया है और ऑफ़लाइन तैयार है।",
      "summarizer": "सारांशकर्ता",
      "paste_notes": "त्वरित सारांश प्राप्त करने के लिए अपने नोट्स पेस्ट करें या PDF अपलोड करें...",
      "summarize_btn": "सारांश बनाएं",
      "generating": "बनाया जा रहा है...",
      "key_takeaways": "मुख्य बातें",
      "next_steps": "अगले कदम",
      "flashcards": "फ्लैशकार्ड",
      "take_quiz": "क्विज़ लें",
      "ready_to_summarize": "सारांश के लिए तैयार",
      
      // --- Bottom Navigation ---
      "nav_home": "होम",
      "nav_summary": "सारांश",
      "nav_cards": "कार्ड्स",
      "nav_quiz": "क्विज़",
      "nav_profile": "प्रोफ़ाइल",

      // --- Home Screen ---
      "hello": "नमस्ते,",
      "ready_to_learn": "सीखने के लिए तैयार हैं?",
      "pro_feature": "प्रो फ़ीचर",
      "hero_title": "AI असिस्टेंट के साथ\nस्मार्ट पढ़ाई करें",
      "hero_subtitle": "तुरंत सारांश, फ्लैशकार्ड और क्विज़ बनाने के लिए नोट्स अपलोड करें।",
      "quick_tools": "त्वरित उपकरण",
      "recent_activity": "हाल की गतिविधि",
      "no_recent_activity": "अभी तक कोई हालिया गतिविधि नहीं। पढ़ाई शुरू करें!",
      
      // --- Flashcard Screen ---
      "study_deck": "स्टडी डेक",
      "paste_deck": "अपना डेक बनाने के लिए नोट्स पेस्ट करें या PDF अपलोड करें...",
      "pdf_btn": "PDF",
      "working": "काम हो रहा है...",
      "generate_cards": "कार्ड बनाएं",
      "ai_building_deck": "AI आपका डेक बना रहा है...",
      "empty_deck": "आपका डेक खाली है",
      "cards_remaining": "कार्ड बाकी हैं",
      "deck_completed": "डेक पूरा हुआ! 🎉 +20 XP",
      
      // --- Quiz Screen ---
      "study_quiz": "स्टडी क्विज़",
      "paste_quiz": "क्विज़ बनाने के लिए नोट्स पेस्ट करें या PDF अपलोड करें...",
      "generate_quiz": "क्विज़ बनाएं",
      "ai_writing_quiz": "AI आपकी क्विज़ लिख रहा है...",
      "empty_quiz": "अभी तक कोई क्विज़ नहीं बनी है",
      "questions_remaining": "प्रश्न बाकी हैं",
      "quiz_completed": "क्विज़ पूरी हुई! 🎉 +50 XP",
      
      // --- Profile Screen ---
      "profile": "प्रोफ़ाइल",
      "current_level": "वर्तमान स्तर",
      "day_streak": "दिन की स्ट्रीक",
      "my_stats": "मेरे आँकड़े",
      "quizzes_taken": "ली गई क्विज़",
      "saved_pdfs": "सहेजे गए PDF",
      "no_activity_yet": "अभी तक कोई गतिविधि नहीं। जाकर पढ़ाई करो!",
      "no_email": "कोई ईमेल नहीं दिया गया",

      // --- Onboarding Screen ---
      "skip": "छोड़ें",
      "welcome_title": "स्मार्ट स्टूडेंट में\nआपका स्वागत है",
      "welcome_desc": "आपका AI-संचालित अध्ययन साथी। आइए सीखने को आसान, तेज़ और मज़ेदार बनाएं।",
      "study_smarter_title": "स्मार्ट पढ़ाई करें,\nकठिन नहीं",
      "study_smarter_desc": "तुरंत सारांश, फ्लैशकार्ड और क्विज़ बनाने के लिए अपने PDF या नोट्स अपलोड करें।",
      "create_account": "खाता बनाएं",
      "signup_desc": "अपनी प्रगति, डेक और अध्ययन स्ट्रीक्स को सहेजने के लिए साइन अप करें।",
      "your_name": "आपका नाम",
      "email_optional": "ईमेल पता (वैकल्पिक)",
      "get_started": "शुरू करें",
      "continue_btn": "जारी रखें",

      "account": "खाता",
      "edit_profile": "प्रोफ़ाइल संपादित करें",
      "data_privacy": "डेटा और गोपनीयता",
      "clear_data": "अध्ययन इतिहास साफ़ करें",
      "clear_data_desc": "अपना XP, स्ट्रीक्स और हाल की गतिविधि रीसेट करें।",
      "logout": "लॉग आउट",
      "cancel": "रद्द करें",
      "save": "सहेजें",
      "confirm": "पुष्टि करें",
      "about_app": "स्मार्ट स्टूडेंट के बारे में",

      "notifications": "सूचनाएं",
      "study_reminders": "अध्ययन अनुस्मारक",
      "reminders_sub": "अपनी स्ट्रीक बनाए रखने के लिए सूचना प्राप्त करें।",
      "help_support": "सहायता और समर्थन",
      "send_feedback": "प्रतिक्रिया भेजें",
      "privacy_policy": "गोपनीयता नीति",
    },
    
    "Telugu": {
      // --- Settings & Summarizer ---
      "settings": "సెట్టింగ్‌లు",
      "generation_mode": "జనరేషన్ మోడ్",
      "cloud_ai": "క్లౌడ్ AIని ఉపయోగించండి (సిఫార్సు చేయబడింది)",
      "cloud_ai_sub": "అధునాతన AI కోసం ఇంటర్నెట్ అవసరం.",
      "offline_ai_sub": "ఆఫ్‌లైన్ మోడ్ యాక్టివ్. స్థానిక అల్గారిథమ్‌లను ఉపయోగిస్తుంది.",
      "study_language": "అధ్యయన భాష",
      "download_req": "ఆఫ్‌లైన్ అనువాదం కోసం ఒకసారి 30MB డౌన్‌లోడ్ అవసరం.",
      "download_btn": "ప్యాక్ డౌన్‌లోడ్ చేయండి",
      "downloading": "డౌన్‌లోడ్ అవుతోంది ~30MB...",
      "ready_offline": "ప్యాక్ డౌన్‌లోడ్ చేయబడింది మరియు ఆఫ్‌లైన్‌లో సిద్ధంగా ఉంది.",
      "summarizer": "సారాంశం",
      "paste_notes": "శీఘ్ర సారాంశం పొందడానికి మీ నోట్స్ అతికించండి లేదా PDFని అప్‌లోడ్ చేయండి...",
      "summarize_btn": "సారాంశం చేయండి",
      "generating": "సృష్టిస్తోంది...",
      "key_takeaways": "ముఖ్య అంశాలు",
      "next_steps": "తదుపరి దశలు",
      "flashcards": "ఫ్లాష్‌కార్డ్‌లు",
      "take_quiz": "క్విజ్ తీసుకోండి",
      "ready_to_summarize": "సారాంశానికి సిద్ధంగా ఉంది",
      
      // --- Bottom Navigation ---
      "nav_home": "హోమ్",
      "nav_summary": "సారాంశం",
      "nav_cards": "కార్డులు",
      "nav_quiz": "క్విజ్",
      "nav_profile": "ప్రొఫైల్",

      // --- Home Screen ---
      "hello": "హలో,",
      "ready_to_learn": "నేర్చుకోవడానికి సిద్ధంగా ఉన్నారా?",
      "pro_feature": "ప్రో ఫీచర్",
      "hero_title": "AI అసిస్టెంట్‌తో\nస్మార్ట్‌గా చదవండి",
      "hero_subtitle": "తక్షణమే సారాంశాలు, ఫ్లాష్‌కార్డ్‌లు మరియు క్విజ్‌లను రూపొందించడానికి నోట్స్‌ని అప్‌లోడ్ చేయండి.",
      "quick_tools": "శీఘ్ర సాధనాలు",
      "recent_activity": "ఇటీవలి కార్యాచరణ",
      "no_recent_activity": "ఇంకా ఇటీవలి కార్యాచరణ లేదు. చదవడం ప్రారంభించండి!",
      
      // --- Flashcard Screen ---
      "study_deck": "స్టడీ డెక్",
      "paste_deck": "మీ డెక్‌ను రూపొందించడానికి నోట్స్ అతికించండి లేదా PDF అప్‌లోడ్ చేయండి...",
      "pdf_btn": "PDF",
      "working": "పనిచేస్తోంది...",
      "generate_cards": "కార్డులను రూపొందించండి",
      "ai_building_deck": "AI మీ డెక్‌ను నిర్మిస్తోంది...",
      "empty_deck": "మీ డెక్ ఖాళీగా ఉంది",
      "cards_remaining": "కార్డులు మిగిలి ఉన్నాయి",
      "deck_completed": "డెక్ పూర్తయింది! 🎉 +20 XP",
      
      // --- Quiz Screen ---
      "study_quiz": "స్టడీ క్విజ్",
      "paste_quiz": "క్విజ్ రూపొందించడానికి నోట్స్ అతికించండి లేదా PDF అప్‌లోడ్ చేయండి...",
      "generate_quiz": "క్విజ్‌ని రూపొందించండి",
      "ai_writing_quiz": "AI మీ క్విజ్‌ని రాస్తోంది...",
      "empty_quiz": "ఇంకా క్విజ్ రూపొందించబడలేదు",
      "questions_remaining": "ప్రశ్నలు మిగిలి ఉన్నాయి",
      "quiz_completed": "క్విజ్ పూర్తయింది! 🎉 +50 XP",
      
      // --- Profile Screen ---
      "profile": "ప్రొఫైల్",
      "current_level": "ప్రస్తుత స్థాయి",
      "day_streak": "డే స్ట్రీక్",
      "my_stats": "నా గణాంకాలు",
      "quizzes_taken": "తీసుకున్న క్విజ్‌లు",
      "saved_pdfs": "సేవ్ చేయబడిన PDFలు",
      "no_activity_yet": "ఇంకా ఎలాంటి కార్యాచరణ లేదు. వెళ్లి చదువుకో!",
      "no_email": "ఇమెయిల్ అందించబడలేదు",

      // --- Onboarding Screen ---
      "skip": "దాటవేయి",
      "welcome_title": "స్మార్ట్ స్టూడెంట్‌కు\nస్వాగతం",
      "welcome_desc": "మీ AI-ఆధారిత అధ్యయన సహచరుడు. నేర్చుకోవడాన్ని సులభం, వేగంగా మరియు మరింత సరదాగా చేద్దాం.",
      "study_smarter_title": "స్మార్ట్‌గా చదవండి,\nకష్టపడి కాదు",
      "study_smarter_desc": "తక్షణమే సారాంశాలు, ఫ్లాష్‌కార్డ్‌లు మరియు క్విజ్‌లను రూపొందించడానికి మీ PDFలు లేదా నోట్స్‌ని అప్‌లోడ్ చేయండి.",
      "create_account": "ఖాతా సృష్టించండి",
      "signup_desc": "మీ పురోగతి, డెక్‌లు మరియు స్టడీ స్ట్రీక్స్‌ను సేవ్ చేయడానికి సైన్ అప్ చేయండి.",
      "your_name": "మీ పేరు",
      "email_optional": "ఇమెయిల్ చిరునామా (ఐచ్ఛికం)",
      "get_started": "ప్రారంభించండి",
      "continue_btn": "కొనసాగించు",

      "account": "ఖాతా",
      "edit_profile": "ప్రొఫైల్‌ను సవరించండి",
      "data_privacy": "డేటా & గోప్యత",
      "clear_data": "చరిత్రను క్లియర్ చేయండి",
      "clear_data_desc": "మీ XP, స్ట్రీక్స్ మరియు ఇటీవలి కార్యాచరణను రీసెట్ చేయండి.",
      "logout": "లాగ్ అవుట్",
      "cancel": "రద్దు చేయి",
      "save": "సేవ్ చేయండి",
      "confirm": "నిర్ధారించండి",
      "about_app": "స్మార్ట్ స్టూడెంట్ గురించి",

      "notifications": "నోటిఫికేషన్లు",
      "study_reminders": "అధ్యయన రిమైండర్లు",
      "reminders_sub": "మీ స్ట్రీక్‌ను కొనసాగించడానికి నోటిఫికేషన్ పొందండి.",
      "help_support": "సహాయం & మద్దతు",
      "send_feedback": "అభిప్రాయాన్ని పంపండి",
      "privacy_policy": "గోప్యతా విధానం",
    },
    
    "Tamil": {
      // --- Settings & Summarizer ---
      "settings": "அமைப்புகள்",
      "generation_mode": "உருவாக்கும் முறை",
      "cloud_ai": "கிளவுட் AI ஐப் பயன்படுத்து (பரிந்துரைக்கப்படுகிறது)",
      "cloud_ai_sub": "மேம்பட்ட AI க்கு இணையம் தேவை.",
      "offline_ai_sub": "ஆஃப்லைன் முறை செயலில் உள்ளது. உள்ளூர் அல்காரிதம்களைப் பயன்படுத்துகிறது.",
      "study_language": "படிப்பு மொழி",
      "download_req": "ஆஃப்லைன் மொழிபெயர்ப்பிற்கு ஒரு முறை 30MB பதிவிறக்கம் தேவை.",
      "download_btn": "பேக்கை பதிவிறக்கவும்",
      "downloading": "பதிவிறக்குகிறது ~30MB...",
      "ready_offline": "பேக் பதிவிறக்கப்பட்டது மற்றும் ஆஃப்லைனில் தயாராக உள்ளது.",
      "summarizer": "சுருக்கம்",
      "paste_notes": "விரைவான சுருக்கத்தைப் பெற உங்கள் குறிப்புகளை ஒட்டவும் அல்லது PDF ஐ பதிவேற்றவும்...",
      "summarize_btn": "சுருக்கவும்",
      "generating": "உருவாக்குகிறது...",
      "key_takeaways": "முக்கிய குறிப்புகள்",
      "next_steps": "அடுத்த படிகள்",
      "flashcards": "ஃபிளாஷ் கார்டுகள்",
      "take_quiz": "வினாடி வினா எடு",
      "ready_to_summarize": "சுருக்கத் தயார்",
      
      // --- Bottom Navigation ---
      "nav_home": "முகப்பு",
      "nav_summary": "சுருக்கம்",
      "nav_cards": "அட்டைகள்",
      "nav_quiz": "வினாடி வினா",
      "nav_profile": "சுயவிவரம்",

      // --- Home Screen ---
      "hello": "வணக்கம்,",
      "ready_to_learn": "கற்க தயாரா?",
      "pro_feature": "ப்ரோ அம்சம்",
      "hero_title": "AI உதவியாளருடன்\nஸ்மார்ட்டாக படிக்கவும்",
      "hero_subtitle": "சுருக்கங்கள், ஃபிளாஷ் கார்டுகள் மற்றும் வினாடி வினாக்களை உடனடியாக உருவாக்க குறிப்புகளைப் பதிவேற்றவும்.",
      "quick_tools": "விரைவான கருவிகள்",
      "recent_activity": "சமீபத்திய செயல்பாடு",
      "no_recent_activity": "இதுவரை எந்த சமீபத்திய செயல்பாடும் இல்லை. படிக்கத் தொடங்குங்கள்!",
      
      // --- Flashcard Screen ---
      "study_deck": "ஸ்டடி டெக்",
      "paste_deck": "உங்கள் டெக்கை உருவாக்க குறிப்புகளை ஒட்டவும் அல்லது PDF ஐ பதிவேற்றவும்...",
      "pdf_btn": "PDF",
      "working": "வேலை செய்கிறது...",
      "generate_cards": "கார்டுகளை உருவாக்கு",
      "ai_building_deck": "AI உங்கள் டெக்கை உருவாக்குகிறது...",
      "empty_deck": "உங்கள் டெக் காலியாக உள்ளது",
      "cards_remaining": "கார்டுகள் மீதமுள்ளன",
      "deck_completed": "டெக் முடிந்தது! 🎉 +20 XP",
      
      // --- Quiz Screen ---
      "study_quiz": "ஸ்டடி வினாடி வினா",
      "paste_quiz": "வினாடி வினாவை உருவாக்க குறிப்புகளை ஒட்டவும் அல்லது PDF ஐ பதிவேற்றவும்...",
      "generate_quiz": "வினாடி வினாவை உருவாக்கு",
      "ai_writing_quiz": "AI உங்கள் வினாடி வினாவை எழுதுகிறது...",
      "empty_quiz": "இதுவரை எந்த வினாடி வினாவும் உருவாக்கப்படவில்லை",
      "questions_remaining": "கேள்விகள் மீதமுள்ளன",
      "quiz_completed": "வினாடி வினா முடிந்தது! 🎉 +50 XP",
      
      // --- Profile Screen ---
      "profile": "சுயவிவரம்",
      "current_level": "தற்போதைய நிலை",
      "day_streak": "நாள் ஸ்ட்ரீக்",
      "my_stats": "என் புள்ளிவிவரங்கள்",
      "quizzes_taken": "எடுக்கப்பட்ட வினாடி வினாக்கள்",
      "saved_pdfs": "சேமிக்கப்பட்ட PDFகள்",
      "no_activity_yet": "இதுவரை எந்த செயல்பாடும் இல்லை. போய் படி!",
      "no_email": "மின்னஞ்சல் வழங்கப்படவில்லை",

      // --- Onboarding Screen ---
      "skip": "தவிர்",
      "welcome_title": "ஸ்மார்ட் ஸ்டூடண்டிற்கு\nவரவேற்கிறோம்",
      "welcome_desc": "உங்கள் AI-இயங்கும் படிப்பு துணை. கற்றலை எளிதாகவும், வேகமாகவும், மேலும் வேடிக்கையாகவும் மாற்றுவோம்.",
      "study_smarter_title": "ஸ்மார்ட்டாகப் படியுங்கள்,\nகடினமாக அல்ல",
      "study_smarter_desc": "சுருக்கங்கள், ஃபிளாஷ் கார்டுகள் மற்றும் வினாடி வினாக்களை உடனடியாக உருவாக்க உங்கள் PDFகள் அல்லது குறிப்புகளைப் பதிவேற்றவும்.",
      "create_account": "கணக்கை உருவாக்கு",
      "signup_desc": "உங்கள் முன்னேற்றம், டெக்குகள் மற்றும் படிப்பு ஸ்ட்ரீக்குகளைச் சேமிக்க பதிவு செய்யவும்.",
      "your_name": "உங்கள் பெயர்",
      "email_optional": "மின்னஞ்சல் முகவரி (விரும்பினால்)",
      "get_started": "தொடங்கு",
      "continue_btn": "தொடரவும்",

      "account": "கணக்கு",
      "edit_profile": "சுயவிவரத்தைத் திருத்து",
      "data_privacy": "தரவு & தனியுரிமை",
      "clear_data": "வரலாற்றை அழி",
      "clear_data_desc": "உங்கள் XP, ஸ்ட்ரீக்குகள் மற்றும் சமீபத்திய செயல்பாட்டை மீட்டமைக்கவும்.",
      "logout": "வெளியேறு",
      "cancel": "ரத்துசெய்",
      "save": "சேமி",
      "confirm": "உறுதிப்படுத்து",
      "about_app": "ஸ்மார்ட் மாணவர் பற்றி",

      "notifications": "அறிவிப்புகள்",
      "study_reminders": "படிப்பு நினைவூட்டல்கள்",
      "reminders_sub": "உங்கள் ஸ்ட்ரீக்கை பராமரிக்க அறிவிப்பைப் பெறுங்கள்.",
      "help_support": "உதவி மற்றும் ஆதரவு",
      "send_feedback": "கருத்து அனுப்பவும்",
      "privacy_policy": "தனியுரிமைக் கொள்கை",
    }
  };

  static String get(String key) {
    String currentLang = StorageService.getLanguage();
    if (!_localized.containsKey(currentLang)) currentLang = "English";
    return _localized[currentLang]?[key] ?? _localized["English"]![key] ?? key;
  }
}